'use strict';
// Avoid `console` errors in browsers that lack a console.
!function(){for(var o,e=function(){},n=["assert","clear","count","debug","dir","dirxml","error","exception","group","groupCollapsed","groupEnd","info","log","markTimeline","profile","profileEnd","table","time","timeEnd","timeStamp","trace","warn"],r=n.length,i=window.console=window.console||{};r--;)o=n[r],i[o]||(i[o]=e)}();
// smooth-scroller - Javascript lib to handle smooth scrolling * v0.1.2
!function(a){a.fn.smoothScroller=function(b){b=a.extend({},a.fn.smoothScroller.defaults,b);var c=a(this);return a(b.scrollEl).animate({scrollTop:c.offset().top-a(b.scrollEl).offset().top-b.offset},b.speed,b.ease,function(){var a=c.attr("id");a.length&&(history.pushState?history.pushState(null,null,"#"+a):document.location.hash=a),c.trigger("smoothScrollerComplete")}),this},a.fn.smoothScroller.defaults={speed:400,ease:"swing",scrollEl:"body,html",offset:0},a("body").on("click","[data-smoothscroller]",function(b){b.preventDefault();var c=a(this).attr("href");0===c.indexOf("#")&&a(c).smoothScroller()})}(jQuery);
// toc - jQuery Table of Contents Plugin  * v0.3.2
!function(t){t.fn.toc=function(e){var o,i=this,n=t.extend({},jQuery.fn.toc.defaults,e),r=t(n.container),s=t(n.selectors,r),l=[],a=n.activeClass,c=function(e,o){if(n.smoothScrolling&&"function"==typeof n.smoothScrolling){e.preventDefault();var r=t(e.target).attr("href");n.smoothScrolling(r,n,o)}t("a",i).removeClass(a),t(e.target).addClass(a)},f=function(e){o&&clearTimeout(o),o=setTimeout(function(){for(var e,o=t(window).scrollTop(),r=Number.MAX_VALUE,s=0,c=0,f=l.length;f>c;c++){var h=Math.abs(l[c]-o);r>h&&(s=c,r=h)}t("a",i).removeClass(a),e=t("a:eq("+s+")",i).addClass(a),n.onHighlight(e)},50)};return n.highlightOnScroll&&(t(window).bind("scroll",f),f()),this.each(function(){var e=t(this),o=t(n.listType);o.addClass(n.listTypeClass),s.each(function(i,r){var s=t(r);l.push(s.offset().top-n.highlightOffset);var a=n.anchorName(i,r,n.prefix);if(r.id!==a){t("<span/>").attr("id",a).insertBefore(s)}var h=t("<a/>").text(n.headerText(i,r,s)).addClass(n.itemClass(i,r,s,n.prefix)).attr("href","#"+a).bind("click",function(o){t(window).unbind("scroll",f),c(o,function(){}),t(window).bind("scroll",f),e.trigger("selected",t(this).attr("href"))});o.append(h)}),e.append(o)})},jQuery.fn.toc.defaults={container:"article",listType:"<div/>",listTypeClass:"list-group",selectors:"h2,h3,h4",smoothScrolling:function(e,o,i){t(e).smoothScroller({offset:o.scrollToOffset}).on("smoothScrollerComplete",function(){i()})},scrollToOffset:0,prefix:"toc",activeClass:"active",onHighlight:function(){},highlightOnScroll:!0,highlightOffset:100,anchorName:function(t,e,o){return o+t},headerText:function(t,e,o){return o.text()},itemClass:function(t,e,o,i){return"list-group-item"}}}(jQuery);
// scrollTo - jQuery Scroll to Plugin
;(function($){var h=$.scrollTo=function(a,b,c){$(window).scrollTo(a,b,c)};h.defaults={axis:'xy',duration:parseFloat($.fn.jquery)>=1.3?0:1,limit:true};h.window=function(a){return $(window)._scrollable()};$.fn._scrollable=function(){return this.map(function(){var a=this,isWin=!a.nodeName||$.inArray(a.nodeName.toLowerCase(),['iframe','#document','html','body'])!=-1;if(!isWin)return a;var b=(a.contentWindow||a).document||a.ownerDocument||a;return/webkit/i.test(navigator.userAgent)||b.compatMode=='BackCompat'?b.body:b.documentElement})};$.fn.scrollTo=function(e,f,g){if(typeof f=='object'){g=f;f=0}if(typeof g=='function')g={onAfter:g};if(e=='max')e=9e9;g=$.extend({},h.defaults,g);f=f||g.duration;g.queue=g.queue&&g.axis.length>1;if(g.queue)f/=2;g.offset=both(g.offset);g.over=both(g.over);return this._scrollable().each(function(){if(e==null)return;var d=this,$elem=$(d),targ=e,toff,attr={},win=$elem.is('html,body');switch(typeof targ){case'number':case'string':if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(targ)){targ=both(targ);break}targ=$(targ,this);if(!targ.length)return;case'object':if(targ.is||targ.style)toff=(targ=$(targ)).offset()}$.each(g.axis.split(''),function(i,a){var b=a=='x'?'Left':'Top',pos=b.toLowerCase(),key='scroll'+b,old=d[key],max=h.max(d,a);if(toff){attr[key]=toff[pos]+(win?0:old-$elem.offset()[pos]);if(g.margin){attr[key]-=parseInt(targ.css('margin'+b))||0;attr[key]-=parseInt(targ.css('border'+b+'Width'))||0}attr[key]+=g.offset[pos]||0;if(g.over[pos])attr[key]+=targ[a=='x'?'width':'height']()*g.over[pos]}else{var c=targ[pos];attr[key]=c.slice&&c.slice(-1)=='%'?parseFloat(c)/100*max:c}if(g.limit&&/^\d+$/.test(attr[key]))attr[key]=attr[key]<=0?0:Math.min(attr[key],max);if(!i&&g.queue){if(old!=attr[key])animate(g.onAfterFirst);delete attr[key]}});animate(g.onAfter);function animate(a){$elem.animate(attr,f,g.easing,a&&function(){a.call(this,e,g)})}}).end()};h.max=function(a,b){var c=b=='x'?'Width':'Height',scroll='scroll'+c;if(!$(a).is('html,body'))return a[scroll]-$(a)[c.toLowerCase()]();var d='client'+c,html=a.ownerDocument.documentElement,body=a.ownerDocument.body;return Math.max(html[scroll],body[scroll])-Math.min(html[d],body[d])};function both(a){return typeof a=='object'?a:{top:a,left:a}}})(jQuery);
$.extend(jQuery.fn, {
	toplinkwidth: function(){
		var totalContentWidth = jQuery('#navbar-collapse').outerWidth(),
			totalTopLinkWidth = jQuery('#top-link').children('a').outerWidth(true),
			h = (jQuery(window).width() / 2) - (totalContentWidth/2) - totalTopLinkWidth;
		if(h < 0){jQuery(this).hide(); return false;
		} else {
			if(jQuery(window).scrollTop() >= 1){jQuery(this).show();}
			jQuery(this).css({'padding-right': h+'px'}); return true;
		}
	}
});
// Paste plug in after this sentense!
